[package]
name = "aa-bundler-grpc"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Vid201/aa-bundler"
readme = "README.md"
description = """
AA (ERC-4337) Bundler gRPC interfaces
"""
rust-version = "1.69.0"

[dependencies]
aa-bundler-bundler = { path = "../bundler" }
aa-bundler-contracts = { path = "../contracts" }
aa-bundler-primitives = { path = "../primitives" }
aa-bundler-uopool = { path = "../uopool" }

anyhow = "1"
arrayref = "0.3"
async-trait = "0.1"
dashmap = "5.4.0"
ethers = { workspace = true }
parking_lot = "0.12"
prost = "0.11"
serde_json = "1"
tokio = { version = "1.18", features = ["full"] }
tonic = { version = "0.8", default-features = false, features = [
    "codegen",
    "prost",
    "transport",
] }
tracing = { workspace = true }

[build-dependencies]
prost-build = "0.11"
protobuf-src = "1.1.0"
tonic-build = "0.8"
