[package]
name = "aa-bundler-grpc"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) Bundler gRPC interfaces
"""

[dependencies]
aa-bundler-bundler = { path = "../bundler" }
aa-bundler-contracts = { path = "../contracts" }
aa-bundler-primitives = { path = "../primitives" }
aa-bundler-uopool = { path = "../uopool" }

anyhow = "1"
arrayref = "0.3"
async-trait = "0.1"
dashmap = "5.4.0"
ethers = { workspace = true }
parking_lot = "0.12"
prost = "0.11"
serde_json = "1"
tokio = { workspace = true }
tonic = { version = "0.8", default-features = false, features = [
    "codegen",
    "prost",
    "transport",
] }
tracing = { workspace = true }

[build-dependencies]
prost-build = "0.11"
protobuf-src = "1.1.0"
tonic-build = "0.8"
