services:
  geth-dev:
    image: ethereum/client-go:v1.14.8
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - --miner.gaslimit=12000000
      - --http
      - --http.api=personal,eth,net,web3,debug
      - --allow-insecure-unlock
      - --rpc.allow-unprotected-txs
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.addr=0.0.0.0
      - --ws
      - --ws.api=personal,eth,net,web3,debug
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --dev
      - --nodiscover
      - --maxpeers=0
      - --mine
      - --verbosity=2
  fund-signer:
    image: ethereum/client-go:v1.14.8
    entrypoint: 'geth --exec "eth.sendTransaction({from: eth.accounts[0], to: \"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266\", value: web3.toWei(10000, \"ether\")})" attach http://geth-dev:8545'
    depends_on:
      geth-dev:
        condition: service_started