[package]
name = "aa-bundler"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
description = "AA - Bundler implementation"
default-run = "bundler"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
ethereum-types = { version = "0.14", features = ["codec"] }
ethers = "1.0.0"
expanded-pathbuf = "0.1"
jsonrpsee = { version = "0.15", features = ["server", "macros"] }
ron = "0.8"
serde = "1"
tokio = { version = "1.18", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[[bin]]
path = "bin/bundler.rs"
name = "bundler"

[[bin]]
path = "bin/bundler-uopool.rs"
name = "bundler-uopool"

[[bin]]
path = "bin/bundler-rpc.rs"
name = "bundler-rpc"
