[package]
name = "aa-bundler"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
description = "AA - Bundler implementation"
default-run = "bundler"

[dependencies]
anyhow = "1"

[[bin]]
path = "bin/bundler.rs"
name = "bundler"
