[workspace]
members = [
    "bin/bundler",
    "crates/bundler",
    "crates/contracts",
    "crates/grpc",
    "crates/primitives",
    "crates/rpc",
    "crates/uopool",
    "tests",
]
default-members = ["bin/bundler"]

[profile.debug-fast]
inherits = "release"
debug = true

[patch]
[patch.crates-io]
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "3d8ca6641d2e72448c23f4596f769c8fd1c784d1" }
