[package]
name = "silius-contracts"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) bundler smart contract interfaces
"""

[dependencies]
silius-primitives = { path = "../primitives" }

anyhow = "1"
ethers = { workspace = true }
ethers-providers = "2.0.1"
lazy_static = "1.4.0"
serde = "1"
serde_json = "1"
thiserror = "1"

[dev-dependencies]
tokio = { workspace = true }

[build-dependencies]
anyhow = "1"
ethers = { workspace = true, features = ["solc-full"] }
ethers-solc = "2.0.4"
