[package]
name = "aa-bundler-contracts"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Vid201/aa-bundler"
readme = "README.md"
description = """
AA (ERC-4337) Bundler smart contract interfaces
"""
rust-version = "1.69.0"

[dependencies]
aa-bundler-primitives = { path = "../primitives" }

anyhow = "1"
ethers = { workspace = true }
ethers-providers = "2.0.1"
lazy_static = "1.4.0"
serde = "1"
serde_json = "1"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1.18", features = ["full"] }

[build-dependencies]
anyhow = "1"
ethers = { workspace = true, features = ["solc-full"] }
