[package]
name = "aa-bundler-primitives"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Vid201/aa-bundler"
readme = "README.md"
description = """
AA (ERC-4337) Bundler commonly used types
"""
rust-version = "1.67.1"

[dependencies]
anyhow = "1"
educe = { version = "0.4", features = ["Debug", "Default"] }
ethers = { version = "2.0.1", features = ["solc-full"] }
expanded-pathbuf = "0.1"
jsonrpsee = { version = "0.16", features = ["server", "macros"] }
rustc-hex = "^2.0.1"
serde = "1"
serde_json = "1"

[features]
test-utils = []