[package]
name = "aa-bundler-rpc"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Vid201/aa-bundler"
readme = "README.md"
description = """
AA (ERC-4337) Bundler RPC implementation
"""
rust-version = "1.69.0"

[dependencies]
aa-bundler-grpc = { path = "../grpc" }
aa-bundler-primitives = { path = "../primitives" }

anyhow = "1"
async-trait = "0.1"
ethers = { workspace = true }
git-version = "0.3.5"
jsonrpsee = { version = "0.16", features = ["server", "macros"] }
serde_json = "1"
tonic = { version = "0.8", default-features = false, features = [
    "transport",
] }
