[package]
name = "silius-rpc"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) bundler RPC implementation
"""

[dependencies]
async-trait = { workspace = true }
ethers = { workspace = true }
eyre = { workspace = true }
git-version = "0.3.5"
hyper = { version = "0.14" }
jsonrpsee = { version = "0.18.2", features = ["server", "macros", "client"] }
serde = "1"
serde_json = { workspace = true }
silius-grpc = { path = "../grpc" }
silius-primitives = { path = "../primitives" }
tonic = { version = "0.8", default-features = false, features = ["transport"] }
tower = { version = "0.4.13" }
tower-http = { version = "0.4.1", features = ["cors"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
