[package]
name = "silius-bundler"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) bundler bundling implementation
"""

[dependencies]
silius-contracts = { path = "../contracts" }
silius-primitives = { path = "../primitives" }

anyhow = "1"
ethers = { workspace = true }
tracing = { workspace = true }
