on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  build_and_test:
    name: Rust Abstract Account Bundler Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Setup
        run: |
          make fetch-thirdparty
      - name: Install solc
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo add-apt-repository ppa:ethereum/ethereum-dev
          sudo apt-get update
          sudo apt-get install solc
      - name: Build
        run: |
          make build
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make cargo-test


